$(function(){
				// // 校验密码
				// jQuery.validator.addMethod("pwdrule", function(value, element) {
				// 	var length = value.length;
				// 	var mobile = /^(?=.*[a-zA-Z])(?=.*[0-9])[A-Za-z0-9]{8,18}$/;
				// 	return this.optional(element) || (length == 11 && mobile.test(value));
				// }, "密码必须由字母、数字组成，区分大小写,8-18位");
				
				$("#adduser").validate({
					rules:{
						upname:{
							required:true,
							rangelength:[6,10],
							maxlength:10,
							minlength:6
						},
						urname:{
							required:true,
							rangelength:[2,5],
							maxlength:5,
							minlength:2
						},
						upwd1:{
							required:true,
							rangelength:[8,10],
							maxlength:10,
							minlength:8
							// pwdrule:true
						},
						upwd2:{
							required:true,
							rangelength:[8,10],
							maxlength:10,
							minlength:8,
							equalTo:'#pwd1'
							// pwdrule:true
						},
						uphone:{
							required:true,
							maxlength:11,
							minlength:11
						},
						uaddr:{
							required:true
						},
						uemail:{
							required:true,
							email:true
						}
					},
					messages:{
						upname:{
							required:"用户登录名必输！",
							rangelength:"用户登录名必须在6-10位之间",
							maxlength:"用户登录名必须在6-10位之间",
							minlength:"用户登录名必须在6-10位之间"
						},
						urname:{
							required:"用户姓名必输！",
							rangelength:"用户姓名必须在2-5位之间",
							maxlength:"用户姓名必须在2-5位之间",
							minlength:"用户姓名必须在2-5位之间"
						},
						upwd1:{
							required:"密码必输！",
							rangelength:"用户密码必须在6-10位之间",
							maxlength:"用户密码必须在6-10位之间",
							minlength:"用户密码必须在6-10位之间",
							pwdRule:"密码只能是字母和数字的组合!"
						},
						upwd2:{
							required:"密码必须和上次一致！",
							rangelength:"用户密码必须在6-10位之间",
							maxlength:"用户密码必须在6-10位之间",
							minlength:"用户密码必须在6-10位之间",
							pwdRule:"密码只能是字母和数字的组合!",
							equalTo:'密码必须和上次输入一致!'
						},
						uphone:{
							required:"手机号必输",
							maxlength:"手机号为11位",
							minlength:"手机号为11位"
						},
						uaddr:{
							required:"地址必输"
						},
						uemail:{
							required:"邮箱必输",
							email:"邮箱格式不满足要求"
						}
					},
					onfocusout:function(element){
						$(element).valid();
					}
					,
					submitHandler:function(form){
						$.ajax({
							type:"post",
							url:"http://localhost:8080/Ajaxd01/userInsertController.do?",
							data:
							"upname="+$("#upname").val()+"&"+
							"urname="+$("#urname").val()+"&"+
							"Upwd="+$("#pwd1").val()+"&"+
							"uphone="+$("#uphone").val()+"&"+
							"uaddr="+$("#uaddr").val()+"&"+
							"uhobby="+$("input[type='checkbox']:checked").val()+"&"+
							"uemail="+$("#uemail").val()+"",
							dataType:"jsonp",
							jsonp:"callback",
							success:function(info){
								alert("新增用户成功");
								location.href="table.html";
							},
							error:function(){
								alert("error");
							}
						})
					}
				})
			})